### ISSUE TITLE
Definir arquitetura a ser utilizada para o controle de usuários

### ISSUE THREAD

**Issue by lucasdemoraesc** [DLL-S/ueg-pecacerta-requisitos#3]
Analisar a implementação atual e avaliar os possíveis impactos na adição da funcionalidade de acesso por usuário.
usuário pode ser "Funcionário" ou "Cliente", cada um com escopo de acesso diferente.

- Funcionário pode ser "Gerente" ou "Vendedor".

**Comment by MathCassimiro** [comment]
Para criação e manipulação de usuários, seria interessante apenas criar uma classe usuário e um enumerador para definir os tipos de usuários presentes no sistema. Pensei nessa possibilidade, afim de reaproveitar a estrutura de classes já presente no sistema.
Desta forma, a única diferença seria adicionar um atributo do tipo Usuário nas classes de Funcionário e Cliente.
Para classe de Usuário, decidi alterar alguns atributos que estavam presentes na antiga versão:
![image](https://user-images.githubusercontent.com/28124131/117547687-324b7e00-b007-11eb-8a50-77d758d3b014.png)

Como podemos ver, agora o usuário terá um login, que poderá ser preenchido com seu nome e sobrenome (ex.: MatheusCassimiro, ou MCassimiro), ou até mesmo seu e-mail. Isto facilitará para pessoas que não possuem e-mail (é raro, mas acontece muito rsrs).
A senha terá a obrigatoriedade de ter no mínimo 8 caracteres, dentre estes contendo, letras maiúsculas e minúsculas e caracteres especiais.
Sugeri a criação de um pin para facilitar a operação dentro do sistema. O pin será utilizado em algumas telas do sistema para que o usuário não tenha que digitar sua senha a todo momento, visto que é uma senha complexa e forte.
O pin deverá ser numérico com 4 dígitos não sequenciais.
O pin só pode ser usado para operações dentro do sistema, operação como login, deverá ser utilizada a senha cadastrada.

Penso que poderíamos criar uma configuração para determinados usuários que não precisarão informar a senha para realizar uma operação. Isto poderia ser incluso em usuários que tem o tipo de acesso definidos como gerente.

Teríamos que pensar algum modo de criar uma camada de persistência que retorne qual usuário está logado no momento. Pensar em uma biblioteca para encriptação de senha e pin.

Algumas funcionalidades podem ser adicionadas depois, como por exemplo, no momento da criação do usuário o sistema gere uma senha aleatória para aquele usuário e a envie por e-mail. O mesmo pode ocorrer na opção de esquecimento de senha.

**Comment by lucasdemoraesc** [comment]
## **Trabalhar o diagrama de classes**
### - Usuário
- Mantém a classe usuário, com o campo **login**. Para funcionário utilizando o atributo "login" (Nome de usuário) passado no momento do cadastro. Para clientes, o campo login será preenchido com o CPF ou CNPJ. A senha do funcionário será definida no primeiro acesso. A senha do cliente deve ser gerada automaticamente e resetada no primeiro acesso.

- Primeiro acesso do cliente, verifica a se a coluna "alterarSenhaProximoAcesso" no banco é true, se for pede que a senha seja definida. Caso o cliente esqueça a senha o sistema pede que o mesmo informe o numero de telefone cadastrado, válida exibe a tela de nova senha.

- Caso seja o primeiro acesso do funcionário, deve ser solicitado que o mesmo informe um PIN.

**Comment by lucasdemoraesc** [comment]
@MathCassimiro depois clona esse repositório, coloca sua versão do diagrama de classes no lugar do atual (ueg-pecacerta-requisitos/Modelagem e requisitos/Diagrama de classes/) e commita aí pfvr

**Comment by lucasdemoraesc** [comment]
@MathCassimiro
